web:
  extends:
    file: docker-compose.yml
    service: web
  container_name: package-web-dev
  ports:
  - '9010:9010'
  environment:
  - NODE_ENV=development
  - COMPOSE_PROJECT_NAME=package-dev
  - PORT=9010
  command: >
    sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      fi &&
      npm install &&
      npm run storybook
    '
